# Generated by Django 3.0.5 on 2022-07-14 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='law',
            name='law_image',
            field=models.ImageField(default=1, upload_to='law_image'),
            preserve_default=False,
        ),
    ]
