# Generated by Django 3.0.5 on 2022-07-14 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_law_law_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='law',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
