# Generated by Django 3.0.5 on 2022-07-13 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0002_lregister'),
    ]

    operations = [
        migrations.AddField(
            model_name='lregister',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='register',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lregister',
            name='email',
            field=models.EmailField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='lregister',
            name='enrollment_no',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lregister',
            name='name',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lregister',
            name='password',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='lregister',
            name='phone',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.EmailField(max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='name',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='phone',
            field=models.IntegerField(default=0),
        ),
    ]
