# Generated by Django 3.0.5 on 2022-07-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_auto_20220713_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='lregister',
            name='law',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
