# Generated by Django 3.0.5 on 2022-07-13 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0004_lregister_law'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lregister',
            name='law',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
