# Generated by Django 3.0.5 on 2022-07-13 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0005_auto_20220713_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lregister',
            name='email',
            field=models.EmailField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.EmailField(max_length=20, null=True),
        ),
    ]
