# Generated by Django 3.0.5 on 2022-07-14 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0006_auto_20220713_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='lregister',
            name='lawyer_image',
            field=models.ImageField(default=0, upload_to='lawyer_image'),
        ),
    ]
